### ISSUE TITLE
build gfx2gfx error

### ISSUE THREAD

**Issue by liudonghua123** [matthiaskramm/swftools#54]
I was working on Ubuntu 16.04, I want to build gfx2gfx.
I followed the below steps

```bash
git clone --depth=1 git://github.com/matthiaskramm/swftools ./swftools
cd swftools
./configure
make
cd lib
make
cd ../src
make gfx2gfx
```

and the last step gave me the following error message.

```bash
liudonghua@desktop-ldh:~/code/swftools/src$ make gfx2gfx
gcc -c -DHAVE_CONFIG_H   -I/usr/include/freetype2 -I/usr/include/fontconfig -Ilame -Ilib/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  gfx2gfx.c -o gfx2gfx.o
g++ -DHAVE_CONFIG_H gfx2gfx.o -o gfx2gfx ../lib/libgfxswf.a ../lib/librfxswf.a ../lib/libgfxpdf.a ../lib/libgfx.a ../lib/libbase.a -L/usr/local/lib -lzzip -lgif -ljpeg -lz -lm  -lfontconfig -lfreetype -lfftw3f -lstdc++
/usr/bin/ld: Warning: size of symbol `voidclass' changed from 104 in ../lib/librfxswf.a(abc.o) to 112 in ../lib/librfxswf.a(registry.o)
gfx2gfx.o: In function `main':
gfx2gfx.c:(.text+0xab3): undefined reference to `gfxdevice_pdf_init'
collect2: error: ld returned 1 exit status
Makefile:129: recipe for target 'gfx2gfx' failed
make: *** [gfx2gfx] Error 1
liudonghua@desktop-ldh:~/code/swftools/src$
```

**Comment by liudonghua123** [comment]
I need to install `libpdf` first.
See also https://github.com/johan12345/schoolbook2pdf#how-to
