### ISSUE TITLE
Code doesn't build on Manjaro / ArchLinux

### ISSUE THREAD

**Issue by thibaultserti** [matthiaskramm/swftools#158]
Run build with 9.2 version and with last github version. I got the same error.

```console
$ make
...
gcc -DHAVE_CONFIG_H -g -shared gfx.o -o gfx.so ../libgfxpdf.a ../libgfxswf.a  ../librfxswf.a ../libgfx.a ../libbase.a  -lpython2.7 /usr/lib/python2.7/site-packages/PIL/_imaging.so -L/usr/local/lib -lzzip -lgif -ljpeg -lpdf -lz -lm  -lfontconfig -lfreetype -lfftw3f -lstdc++
/usr/bin/ld: ../libgfx.a(poly.o):(.data.rel.local+0x0): multiple definition of `point_type'; ../libgfx.a(convert.o):(.bss+0x0): first defined here
/usr/bin/ld: ../libgfx.a(stroke.o):(.bss+0x0): multiple definition of `point_type'; ../libgfx.a(convert.o):(.bss+0x0): first defined here
/usr/bin/ld: ../libgfx.a(wind.o):(.bss+0x20): multiple definition of `point_type'; ../libgfx.a(convert.o):(.bss+0x0): first defined here
/usr/bin/ld: ../libgfx.a(xrow.o):(.bss+0x0): multiple definition of `point_type'; ../libgfx.a(convert.o):(.bss+0x0): first defined here
/usr/bin/ld: ../libgfx.a(moments.o):(.bss+0x0): multiple definition of `point_type'; ../libgfx.a(convert.o):(.bss+0x0): first defined here
/usr/bin/ld: ../libgfx.a(active.o):(.bss+0x0): multiple definition of `point_type'; ../libgfx.a(convert.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:42: gfx.so] Error 1
```

Probably the same type of errors as #157 ...

**Comment by Layerex** [comment]
I have that error too on Artix
